mystudy/cms/urls.py
from django.urls import path
from cms import views


app_name = 'cms'
urlpatterns = [
    # 事件
    path('affair/', views.affair_list, name='affair_list'),  # 一覧
    path('affair/<int:affair_id>/', views.affair_detail, name='affair_detail')  # 詳細
]

mystudy/mystudy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
]

mystudy/cms/models.py
from django.db import models


class Affair(models.Model):
    """事件情報"""
    place = models.CharField('町名', max_length=255)
    name = models.CharField('事件名', max_length=255, blank=True)
    time = models.CharField('発生時刻', max_length=127)
    content = models.TextField('事件内容', blank=True)

    def __str__(self):
        return self.name

mystudy/cms/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from cms.models import Affair


def affair_list(request):
    """事件の一覧"""
    affairs = Affair.objects.all().order_by('-id')
    return render(request,
                  'cms/affair_list.html',  # 使用するテンプレート
                  {'affairs': affairs})  # テンプレートに渡すデータ


def affair_detail(request, affair_id=None):
    """事件の詳細"""
    detail = get_object_or_404(Affair, pk=affair_id)

    return render(request, 'cms/affair_detail.html', {'detail': detail})

mystudy/cms/templates/cms/affair_detail.html
{% extends "cms/base.html" %}
{% load bootstrap4 %}

{% block title %}事件の詳細{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">事件の詳細</h4>
    <p>町名　　：{{ detail.place }}</p>
    <p>事件名　：{{ detail.name }}</p>
    <p>発生時刻：{{ detail.time }}</p>
    <p><div>事件内容:</div>{{ detail.content }}
    </p>
    <a href="{% url 'cms:affair_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

mystudy/cms/templates/cms/affair_list.html
{% extends "cms/base.html" %}

{% block title %}事件の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">事件の一覧</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">町名</th>
          <th scope="col">発生時刻</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for affair in affairs %}
        <tr>
          <th scope="row">{{ affair.id }}</th>
          <td>{{ affair.place }}</td>
          <td>{{ affair.time }}</td>
          <td>
            <a href="{% url 'cms:affair_detail' affair_id=affair.id %}" class="btn btn-outline-primary btn-sm">詳細</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

mystudy/cms/templates/cms/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My study{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'cms/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>